# Generated by Django 4.2 on 2024-10-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='age_range',
            field=models.CharField(choices=[('enfants', 'Enfants'), ('adolescents', 'Adolescents'), ('jeunes_adultes', 'Jeunes adultes'), ('adultes', 'Adultes'), ('seniors', 'Seniors'), ('non_specifie', 'Non spécifié')], default='non_specifie', max_length=20),
            preserve_default=False,
        ),
    ]
