# Generated by Django 4.2 on 2024-10-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='difficulty_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='quote',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='suggested_tags',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='visibility_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='age_range',
            field=models.CharField(choices=[('enfants', 'Enfants (-12)'), ('adolescents', 'Adolescents (12-18)'), ('jeunes_adultes', 'Jeunes adultes(-18-30)'), ('adultes', 'Adultes(30-50)'), ('seniors', 'Seniors(50+)'), ('non_specifie', 'Non spécifié')], max_length=20),
        ),
    ]
