# Generated by Django 4.2 on 2024-10-28 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0003_feedback'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together=set(),
        ),
    ]
