# Generated by Django 5.1.2 on 2024-10-22 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BMICalculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('weight', models.FloatField(help_text='Weight in kilograms')),
                ('height', models.FloatField(help_text='Height in cm')),
                ('bmi', models.FloatField(blank=True, editable=False, null=True)),
            ],
        ),
    ]
