# Generated by Django 5.1.2 on 2024-10-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmicalculator', '0003_advice_bmicalculator_advice'),
    ]

    operations = [
        migrations.AddField(
            model_name='advice',
            name='bmi_category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='advice',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='advice',
            name='text',
            field=models.TextField(),
        ),
    ]
