# Generated by Django 5.1.2 on 2024-10-27 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmicalculator', '0004_advice_bmi_category_advice_gender_alter_advice_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bmicalculator',
            name='advice',
        ),
        migrations.DeleteModel(
            name='Advice',
        ),
    ]
