# Generated by Django 5.1.2 on 2024-10-27 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmicalculator', '0005_remove_bmicalculator_advice_delete_advice'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('daily_calories', models.PositiveIntegerField(help_text='Recommended daily caloric intake')),
                ('carbs_percentage', models.FloatField(help_text='Percentage of daily calories from carbohydrates')),
                ('protein_percentage', models.FloatField(help_text='Percentage of daily calories from protein')),
                ('fats_percentage', models.FloatField(help_text='Percentage of daily calories from fats')),
                ('description', models.TextField(blank=True, help_text='Additional recommendations', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='bmicalculator',
            name='nutrition_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bmicalculator.nutritionplan'),
        ),
    ]
