# Generated by Django 5.1.2 on 2024-10-27 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmicalculator', '0007_remove_nutritionplan_carbs_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionplan',
            name='bmi_calculator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bmicalculator.bmicalculator'),
        ),
    ]
