# Generated by Django 5.1.1 on 2024-10-25 13:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sujet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('statut', models.CharField(choices=[('non_resolu', 'Non Résolu'), ('resolu', 'Résolu')], default='non_resolu', max_length=20)),
            ],
        ),
    ]
